// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// process_fastq
void process_fastq(std::string infile, std::string out_prefix, int buffer_size);
RcppExport SEXP qckit_process_fastq(SEXP infileSEXP, SEXP out_prefixSEXP, SEXP buffer_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type infile(infileSEXP);
    Rcpp::traits::input_parameter< std::string >::type out_prefix(out_prefixSEXP);
    Rcpp::traits::input_parameter< int >::type buffer_size(buffer_sizeSEXP);
    process_fastq(infile, out_prefix, buffer_size);
    return R_NilValue;
END_RCPP
}
