# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calculate Over Rep seqs
#'
#' Description
#' @param m
#'
#'
NULL

#' calculate Over Rep seqs
#'
#' Description
#' @param m
#'
#'
#'
NULL

#' calculate Over Rep seqs
#'
#' Description
#' @param m
#'
NULL

process_fastq <- function(infile, out_prefix, buffer_size) {
    invisible(.Call('qckit_process_fastq', PACKAGE = 'qckit', infile, out_prefix, buffer_size))
}

qual_score_per_read <- function(infile) {
    .Call('qckit_qual_score_per_read', PACKAGE = 'qckit', infile)
}

gc_per_read <- function(infile) {
    .Call('qckit_gc_per_read', PACKAGE = 'qckit', infile)
}

calc_over_rep_seq <- function(infile, out_prefix, min_size = 5L, buffer_size = 1000000L) {
    .Call('qckit_calc_over_rep_seq', PACKAGE = 'qckit', infile, out_prefix, min_size, buffer_size)
}

