# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

process_fastq <- function(infile, out_prefix, buffer_size) {
    invisible(.Call('qckit_process_fastq', PACKAGE = 'qckit', infile, out_prefix, buffer_size))
}

